version: '3'
services:
  vprodb:
    image: kirupa17/vprosql:1.0.0
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  vproapp:
    image: kirupa17/vprofileapp:1.0.0
    ports: 
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  
  vproweb:
    image: kirupa17/vproweb:1.0.0
    ports:
      - "8070:8070"
    

volumes:
  vprodbdata: {}
  vproappdata: {}